### ISSUE TITLE
Not working on WSL 2

### ISSUE THREAD

**Issue by 8549** [s-arash/VSCodeAlloyExtension#1]
The extension is installed on a WSL2 Ubuntu 18.04 remote workspace. From the bash terminal (both built in in VS Code) and from the Ubuntu standalone app running `java -v` returns the version number so java is available and in the path. Running `java -jar ~/.vscode-server/extensions/arashsahebolamri.alloy-0.6.0/extensionsorg.alloytools.alloy.dist.jar` works as intended.

**Comment by s-arash** [comment]
I haven't tested it on WSL2. I _have_ tested it on WSL 1. 
Are you using the VS Code remote-WSL extension or are you running VS Code on WSL2? Do you get the Alloy GUI when running the jar directly on WSL2?

**Comment by 8549** [comment]
I'm running VS Code remote-WSL. I get the alloy GUI when running the jar from WSL2.

Actually I've fixed the error in the title (it was a problem of classpath because i'm using the Windows JRE from WSL), but now i can't execute commands: they all result in errors. For example the extension says `Running the contributed command: 'alloy.listCommands' failed.` when i try to execute the command `Alloy: List Alloy Commands`. When executing `Alloy: Open Alloy Editor`, nothing happens.

**Comment by s-arash** [comment]
Could you open the output panel in VSCode, select `Alloy Extension` from the dropdown, and paste the contents here?

**Comment by 8549** [comment]
This is the only output:
`alloyJar: /home/[redacted]/.vscode-server/extensions/arashsahebolamri.alloy-0.6.0/org.alloytools.alloy.dist.jar`

**Comment by s-arash** [comment]
And you don't get the "could not start the alloy process" error anymore?

**Comment by 8549** [comment]
Nope.

**Comment by s-arash** [comment]
And you don't get any kind of error in the VS Code window?

**Comment by 8549** [comment]
I get small notifications in the lower right corner of the screen, with the error message i posted before.
Inspecting the remote extension log i get the following
`[2019-11-10 21:54:29.179] [exthost] [error] Error: Language client is not ready yet
	at LanguageClient.sendNotification (/home/[redacted]/.vscode-server/extensions/arashsahebolamri.alloy-0.6.0/node_modules/vscode-languageclient/lib/client.js:1640:19)
	at /home/[redacted]/.vscode-server/extensions/arashsahebolamri.alloy-0.6.0/out/extension.js:28:20
	at v._executeContributedCommand (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:545:863)
	at v.$executeContributedCommand (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:546:217)
	at p._doInvokeHandler (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:664:285)
	at p._invokeHandler (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:663:999)
	at p._receiveRequest (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:662:664)
	at p._receiveOneMessage (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:661:477)
	at /home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:659:754
	at l.fire (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:47:207)
	at _.fire (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:187:274)
	at /home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:816:104
	at l.fire (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:47:207)
	at _.fire (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:187:274)
	at t.PersistentProtocol._receiveMessage (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:191:629)
	at /home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:190:786
	at l.fire (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:47:207)
	at p.acceptChunk (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:184:737)
	at /home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:184:89
	at Socket.t (/home/[redacted]/.vscode-server/bin/86405ea23e3937316009fc27c9361deee66ffbf5/out/vs/server/remoteExtensionHostProcess.js:193:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) alloy.executeAllCommands
`

**Comment by s-arash** [comment]
Do you get any kind of error before running any commands (just after opening an Alloy file)?
It might be something specific to WSL 2. Have you tried using WSL 1? As I understand it, you can switch on the fly between WSL 1 and 2.

**Comment by 8549** [comment]
I don't get any error prior to executing commands. I'm not comfortable with switching WSL versions, if that's even possible.

**Comment by s-arash** [comment]
Alright, I tried the extension on WSL 2, and it worked fine. The problem might be something with your specific setup. I have made a note to add more logging to the extension so that issues like this might leave a trace in the logs.
